#------------------------------------------------------------------------------
# Site configuration
#------------------------------------------------------------------------------
title: Total Computer Care

email: josh@totalcomputercare.com.au

description: >-
  Delivering network solutions for over 20 years.
  Total Computer Care has successfully provided IT technical support services to small and medium sized businesses in Cairns since 1998.
  Our range of products and services allow us to truly be an 'end-to-end' solution provider to small, medium and corporate enterprises.

domain: "totalcomputercare.github.io"

url: "https://totalcomputercare.github.io"

baseurl: ""

company_name: Total Computer Care

company_location: Cairns

company_founded: 1998

contact_email: service@totalcomputercare.com.au

contact_phone: "+61407161960"

office_address:
  - Total Computer Care
  - 8 Katanga Close
  - Smithfield, QLD 4878

postal_address:
  - Total Computer Care
  - P.O. Box 440
  - Smithfield, QLD 4878

partners:
  - name: TeamViewer
    img: /img/partners/TeamViewer.svg
    url: https://get.teamviewer.com/tccremote

  - name: Lenovo
    img: /img/partners/IBM.svg
    url: https://www.lenovo.com/au/en

  - name: Trend Micro
    img: /img/partners/TrendMicro.svg
    url: https://www.trendmicro.com.au

  - name: Intel
    img: /img/partners/Intel.svg
    url: https://www.ibm.com/au

products:
  - type: Hardware
    items:
      - Laptops
      - Desktops
      - Servers
      - Handhelds
      - Hard Disks
      - Mice
      - Keyboards
      - Monitors
      - Wireless
      - Switches
      - Routers
      - Modems
      - Printers/Scanners
      - Multi-function Devices
      - Backup Systems
      - CD/DVD/Bluray Hardware
      - Cables
      - Uninterruptible Power
  - type: Software
    items:
      - Trend Micro Security Software
      - Microsoft Windows
      - Microsoft Office
      - Watchguard

#------------------------------------------------------------------------------
# Jekyll/Build settings
#------------------------------------------------------------------------------
defaults:
  - scope:
      path: img
    values:
      image: true


theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sass-converter

sass:
    sass_dir: _scss
    style: compressed

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
